name: LeddinTheWay
favicon: null
layout_spectrum: 0.8534692572429776
typography_spectrum: 0.7937674857676029
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.767392985522747
  lightness: 0.07545774173922837
  saturation: 0.6595787121914327
  rhythmicContrast: 0.18353710393421352
purpose: []
